# Generated by Django 4.2.10 on 2026-03-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0002_alter_edificio_options_alter_residente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='cantidad_departamentos',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad total de departamentos del edificio.', null=True),
        ),
    ]
