# Generated by Django 4.2.10 on 2026-03-25 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0002_alter_edificio_options_alter_residente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='cantidad_viviendas',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad total de viviendas/departamentos del edificio.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
