# Generated by Django 4.2.10 on 2026-03-17

from django.core.validators import MinValueValidator
from django.db import migrations, models


def _fill_cantidad_viviendas(apps, schema_editor):
    Edificio = apps.get_model('viviendas', 'Edificio')
    Vivienda = apps.get_model('viviendas', 'Vivienda')

    for edificio in Edificio.objects.all().iterator():
        existentes = Vivienda.objects.filter(edificio_id=edificio.id).count()
        valor = edificio.cantidad_viviendas

        if valor is None or valor < 1:
            valor = max(existentes, 1)
        elif valor < existentes:
            valor = existentes

        if edificio.cantidad_viviendas != valor:
            Edificio.objects.filter(pk=edificio.pk).update(cantidad_viviendas=valor)


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0003_edificio_cantidad_departamentos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edificio',
            old_name='cantidad_departamentos',
            new_name='cantidad_viviendas',
        ),
        migrations.RunPython(_fill_cantidad_viviendas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='edificio',
            name='cantidad_viviendas',
            field=models.PositiveIntegerField(
                default=1,
                help_text='Cantidad total de viviendas/departamentos del edificio.',
                validators=[MinValueValidator(1)],
            ),
        ),
    ]
