# Generated by Django 4.2.10 on 2026-03-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0003_edificio_cantidad_viviendas'),
        ('viviendas', '0003_vivienda_monto_expensa'),
    ]

    operations = [
    ]
